### ISSUE TITLE
Public flag for room when creating

### ISSUE THREAD

**Issue by codysherman** [codysherman/2nfm#64]
Public rooms will appear on the homepage, sorted by users in the room count.

**Comment by EnriqueGalindo** [comment]
could I claim this?

**Comment by EnriqueGalindo** [comment]
Initially tried to see all rooms under the assumption that all the rooms were public. Under inspection of the documentation at https://www.rtcmulticonnection.org/ we found `publicRoomIdentifier`. I implemented this in line 235 of ReceiverConnection.vue after the connection, and console.logged the results. This returned an empty array, which lead to the discovery that all rooms are private. Currently we are looking in the demos folder in https://github.com/muaz-khan/RTCMultiConnection/tree/master/demos/dashboard in the index.html file. On line 459 there is a comment on making the room public by setting the `publicRoomIdentifier` to the name of the room. I hard coded this into the StreamerConnection.vue on line 68 to see if I could get something in my console log. Upon running this I received an `array(0)` instead of a `[]`. I am unsure why this change occurred, or if it has any relevance.
